on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 23 * * *'

name: build-quarto-gt-examples-site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Install package
        run: R CMD INSTALL .

      - name: Build and deploy pkgdown site
        run: |
          Rscript -e 'gt:::write_gt_examples_qmd_files()'

      - name: Render site
        run: |
          quarto render gt_qmd_examples

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: 'gt_qmd_examples/_site'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          # these all default to 'true'
          enable-pull-request-comment: false
          enable-commit-comment: true
          enable-commit-status: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
