on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: quarto-connect-gt-examples-site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Print Quarto version
        run: |
          quarto --version

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            gt
            shiny
            tidyverse
            dplyr
            tidyr
            ggplot2
            lubridate
            paletteer
            janitor
            rsconnect
            any::sessioninfo
          dependencies: '"hard"'

      - name: Install package
        run: R CMD INSTALL .

      - name: Generate Quarto files for website
        run: |
          Rscript -e 'gt:::write_gt_examples_qmd_files()'

      - name: Build Quarto site
        run: |
          quarto render gt_qmd_examples

      - name: Publish to Connect
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: connect
          render: false
          path: gt_qmd_examples
          CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
